---
- name: Install Spark
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - name: Replace wget config file
      copy: src=files/etc-wgetrc dest=/etc/wgetrc
  roles:
    - {role: ansible-scripts/ansible-bdas/roles/hdp_hadoop_common }
    - {role: ansible-scripts/ansible-bdas/roles/spark_standalone }
  tasks:
    - name: Create .profile for vagrant user
      template: src=templates/vagrant-profile.j2
                dest=/home/vagrant/.profile
                owner=vagrant
                mode="u=rw,g=r,o=r"
